Traceback (most recent call last):
  File "main.py", line 263, in <module>
    main(args)
  File "main.py", line 132, in main
    for p in model.roi_head.parameters():
  File "/home/zhiyilai/miniconda3/envs/vt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'DETR' object has no attribute 'roi_head'
Traceback (most recent call last):
  File "main.py", line 263, in <module>
    main(args)
  File "main.py", line 132, in main
    for p in model.roi_head.parameters():
  File "/home/zhiyilai/miniconda3/envs/vt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'DETR' object has no attribute 'roi_head'
Traceback (most recent call last):
  File "main.py", line 263, in <module>
    main(args)
  File "main.py", line 132, in main
    for p in model.roi_head.parameters():
  File "/home/zhiyilai/miniconda3/envs/vt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'DETR' object has no attribute 'roi_head'
Traceback (most recent call last):
  File "main.py", line 263, in <module>
    main(args)
  File "main.py", line 132, in main
    for p in model.roi_head.parameters():
  File "/home/zhiyilai/miniconda3/envs/vt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'DETR' object has no attribute 'roi_head'
Traceback (most recent call last):
  File "/home/zhiyilai/miniconda3/envs/vt/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zhiyilai/miniconda3/envs/vt/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhiyilai/miniconda3/envs/vt/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/zhiyilai/miniconda3/envs/vt/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zhiyilai/miniconda3/envs/vt/bin/python', '-u', 'main.py', '--backbone', 'resnet101', '--batch_size', '1', '--dilation', '--resume', 'https://dl.fbaipublicfiles.com/detr/detr-r101-dc5-a2e86def.pth', '--coco_path', '/mnt/nfs/scratch1/zhiyilai/coco', '--output_dir', '/mnt/nfs/scratch1/zhiyilai/detr_roi/']' returned non-zero exit status 1.
